FROM node:16-alpine as build
WORKDIR /app/client
ADD *.json ./
RUN npm install
ADD . .
RUN npm run build
FROM nginx:1.16.0-alpine
COPY --from=build /app/client/build /usr/share/nginx/html
COPY --from=build /app/client/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]