version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    container_name: client
    ports:
      - 80:80
    networks:
      - helperNetwork
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: always
    container_name: auth
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      CLIENT_PATH: https://helper.plus/
      SERVER_PATH: https://helper.plus:5000/
      MONGO_CONNECTION_STRING: "mongodb+srv://kostyazhirnov:jlL5dBy0tFqYvboE@cluster0.duijhnt.mongodb.net/helper?retryWrites=true&w=majority"
      MAIL_HOST: "smtp.gmail.com"
      MAIL_USER: "kostya.zhirnov@gmail.com"
      MAIL_PASSWORD: "tcjblpofktrommea"
    networks:
      - helperNetwork

networks:
  helperNetwork:
    driver: bridge
